function prob = make_prob()
% Initialize the container struct describing the search problem
prob = struct(...
    'probtype', [],...
    'N', [],...
    'adj', [], ...
    'digr', [], ...
    'coords', [], ...
    'bounds', [],...
    'start', [], ...
    'goal', [], ...
    'occupancy', [], ...
    'axMap', [], ...
    'stops', [],...
    'verbose', [], ...
    'interval', [], ...
    'highlightn', [],...
    'postProcessFcn', [],...
    'allPairsPaths', [], ...
    'costMatrix', [], ...
    'SelectionFcn',@selectionFunc,...
    'CrossoverFraction', 0.75,...
    'CrossoverFcn',@crossoverFuncUnordered,...
    'MutationFcn',@mutationFuncUnordered,...
    'PopulationSize',50,...
    'CreationFcn',@creationFuncUnordered,...
    'EliteCount',10);
end
